; Nomes dos arquivos de som para o webvox

HTML=plugin
/HTML=notify
HEAD=
/HEAD=filedone
TITLE=lembrete
/TITLE=
BODY=
/BODY=
CENTER=buic
/CENTER=
BR=
P=
B=plon
I=msgbell
HR=msgsent
PRE=
/PRE=
TABLE=
/TABLE=
CAPTION=boing
/CAPTION=
TH=
/TH=
TD=
/TD=
TR=
SCRIPT=
/SCRIPT=
IMG=camera
UL=chicote
/UL=
OL=click
/OL=
LI=
MAP=
AREA=
AREA HREF=
A NAME=
A HREF=tchi
/A=
FRAMESET=carro
FRAME=
NOFRAMES=
FORM=blimblom
/FORM=
INPUT=digitar
TEXTAREA=
TEXTAREA=
/TEXTAREA=
SELECT=cliclik
/SELECT=
OPTION=
H1=
/H1=
H2=
/H2=
H3=
/H3=
H4=
/H4=
H5=
/H5=
H6=
/H6=
FONT=
/FONT=
