Lista de comandos

    F1 fala palavra.
    Ctrl+F1 fala resto da linha.
    Ctrl+Shift+F1 soletra resto da linha.
    Alt+F1 fala resto do texto.
    Alt+Shift+F1 soletra resto do texto.
    F2 salvar.
    Ctrl+F2 salvar como.
    Ctrl+Shift+F2 salvar como trocando codificação.
    Alt+F2 memoriza linha.
    F3 Trocar de arquivo.
    Ctrl+F3 Abrir outro arquivo.
    Alt+F3 volta a posição memorizada.
    F4 desligar soletrar.
    Ctrl+F4 configurar.
    Ctrl+Shift+F4 alternar modo de fala.
    Alt+F4 fechar programa.
    F5 buscar.
    Ctrl+F5 repetir busca.
    Shift+F5 buscar para traz.
    Ctrl+Shift+F5 repetir busca para traz.
    F6 Substituir.
    Ctrl+F6 calculo e conversões.
    Ctrl+Shift+F6 troca Tab por 8 espaços.
    F7 remove linha.
    Ctrl+F7 amplia o tamanho da tela.
    F8 fala hora.
    Ctrl+F8 fala data.
    F9 menu de opções.
    Ctrl+F9 limpa o texto.
    Ctrl+Shift+F9 traduz de Português de Portugal para Brasileiro.
    F10 altera margens.
    F11 ativa/desativa corretor ortográfico.
    Shift+F11 reinicia corretor ortográfico.
    F12 abre um link.
    Shift+F12 abre um link fora do Dosvox.
    Ctrl+F12 fala versão do Edivox.

    Alt+F abre menu inserir formatação no texto.
    Alt+I fala formatação na posição do cursor.
    Alt+G cama programa para gerar ou impirimir arquivo DOCX.
    Alt+S  sair para o Microsoft Word.
    Alt+D Chama programa e gera direto arquivo DOC.
    Alt+P Chama programa e imprime direto arquivo DOC.
    Alt+O oculta formatação na tela.
    Alt+M abre menu para trocar o modo de fala da formatação.
    Alt+H Sonoramat, abre sintMat.
    Alt+0 liga voz nativa.
    Alt+1 liga voz na posição 1 da memória.
    Alt+2 liga voz na posição 2 da memória.
    Alt+3 liga voz na posição 3 da memória.

    Home vai para início da linha.
    Shift+Home vai para início da linha selecionando.
    Ctrl+Home vai para início do texto.
    Ctrl+Shift+Home vai para início do texto selecionando bloco.
    End vai para fim da linha.
    Shift+End vai para fim da linha selecionando.
    Ctrl+End vai para fim do texto.
    Ctrl+Shift+End vai para fim do texto selecionando bloco.
    PageUp recua 15 linhas.
    Shift+PageUp recua 15 linhas selecionando bloco.
    Ctrl+PageUp recua uma página.
    Ctrl+Shift+PageUp recua uma página selecionando bloco.
    PageDown avança 15 linhas.
    Shift+PageDown avança 15 linhas selecionando bloco.
    Ctrl+PageDown avança uma página.
    Ctrl+Shift+PageDown avança uma página selecionando bloco.
    Insert ativa/desativa o inserir linha com Enter.
    Ctrl+Insert ou Ctrl+C copia para a área de transferência.
    Shift+Insert ou Ctrl+V cola da área de transferência.
    Delete apaga um caractere a direita do cursor ou texto selecionado na linha. Se no fim da linha, junta a de baixo.
    Ctrl+Delete apaga linha atual.
    Ctrl+Shift+Delete apaga bloco selecionado.

    Seta direita avança um caractere.
    Alt+Seta direita avança um caractere falando com alfabeto fonético. Letra em minusculo quando voz feminina e em maiúsculo quando masculina.
    Shift+Seta direita avança um caractere selecionando.
    Ctrl+Seta direita avança palavra falando, verifica ortografia se ligado.
    Ctrl+Shift+Seta direita avança palavra falando e selecionando, verifica ortografia se ligado.
    Seta esquerda recua um caractere.
    Shift+Seta esquerda recua um caractere selecionando.
    Ctrl+Seta esquerda recua palavra falando, verifica ortografia se ligado.
    Ctrl+Shift+Seta esquerda recua palavra falando e selecionando, verifica ortografia se ligado.
    Seta baixo vai para linha de baixo e a fala.
    Shift+Seta baixo fala e seleciona linha atual e vai para linha de baixo.
    Ctrl+Seta baixo vai para mesma coluna da linha de baixo e fala o caractere.
    Ctrl+Shift+Seta baixo vai para mesma coluna da linha de baixo e fala até o fim da linha.
    Seta cima vai para linha de cima e a fala.
    Shift+Seta cima fala e seleciona linha atual e vai para linha de cima.
    Ctrl+Seta cima vai para mesma coluna da linha de cima e fala o caractere.
    Ctrl+Shift+Seta cima vai para mesma coluna da linha de cima e fala até o fim da linha.

    Ctrl+A Avança para linha em branco.
    Ctrl+Shift+A Avança para linha em branco falando o total de linhas do salto.
    Ctrl+R Recua para linha em branco.
    Ctrl+Shift+R Recua para linha em branco falando o total de linhas do salto.
    Ctrl+N fala nome completo do arquivo.
    Ctrl+Shift+N fala apenas o nome do arquivo.
    Ctrl+Y remove linha.
    Ctrl+Shift+y volta linha removida na posição atual do cursor.
    Ctrl+D apaga à direita.
    Ctrl+Shift+D abre lista dicionários
    Ctrl+Shift+O dicionários on-line
    Ctrl+S apaga à esquerda.
    Ctrl+Q quebra linha. Se no fim da linha junta a de baixo.
    Ctrl+J insere linha na posição atual.
    Shift+Enter fala bloco selecionado.
    Tab ou Ctrl+I tabula, insere quatro espaços.
    Shift+Tab ou Ctrl+Shift+I insere o caractere Tab na posição do cursor.
    Ctrl+T seleciona todo texto como bloco.
    Ctrl+Shift +T Tabula.
    backspace apaga caractere a esquerda do cursor.
    Ctrl+h ou Ctrl+ backspace apaga palavra anterior ao cursor.
    Ctrl+B abre menu de comando de bloco.
    Ctrl+Shift+B fala bloco selecionado, linha inicial, linha final, total de linhas e texto selecionado.
    Ctrl+L fala número da linha, total de linhas e percentual lido.
    Ctrl+Shift+L fala número da página, total de páginas e percentual lido.
    Ctrl+K informa coluna e total de colunas.
    Ctrl+U busca próxima palavra errada a partir da posição atual do cursor, posicionando após a ela, permitindo teclar Ctrl+W para conhecer as sugestões..
    Ctrl+Shift+U busca palavra anterior errada a partir da posição atual do cursor, posicionando após a ela, permitindo teclar Ctrl+W para conhecer as sugestões..
    Ctrl+e aciona letras especiais, depois tecle: a, o, g, p,!,?, C, Q, R, T, W, X, Z.
    Ctrl+X grava e termina.
    Ctrl+G posiciona cursor em uma linha determinada (digitar o número)..
    Ctrl+Shift+G posiciona na página desejada (digitar o número).
    Ctrl+F lê até encontrar um sinal de pontuação (ponto final, ponto de exclamação, interrogação, dois pontos e ponto e vírgula), com exceção do parênteses, da vírgula e do hífen.
    Ctrl+Shift+F soletra até encontrar um sinal de pontuação (ponto final, ponto de exclamação, interrogação, dois pontos e ponto e vírgula), com exceção do parênteses, da vírgula e do hífen.
    Ctrl+Shift+C fala o texto da área de transferência.
    Ctrl+\ disca para o número de telefone onde o cursor está posicionado.
    Ctrl+O liga/desliga falando quantidade de espaços em branco na frente da linha.
    Ctrl+P imprime arquivo pelo Listavox (salva antes).
    Ctrl+Shift+P parágrafo vira bloco.
    Ctrl+W se palavra desconhecida, oferece sugestões, além de opção para Ignorar todas ou Adicionar ao corretor.
    Ctrl+Shift+W Mostra uma lista com o número de repetições das palavras no bloco selecionado.
    Ctrl+Z desfaz ultimo comando de alteração no texto.
    Ctrl+Shift+Z refaz o que foi desfeito.
