icinic   I Ching simplificado -  versão ...
icfinal  Consulta ao I Ching terminada.
icformu  Formule sua pergunta e tecle enter
icmoeda  Aperte uma tecla para jogar uma moeda
icconfig Configuracao:

icajuda
    ('As opcoes sao:');
    ('    D - exibe Diagnóstico');
    ('    L - exibe Linhas Móveis');
    ('    P - exibe Prognóstico');
    ('    G - Grava o texto completo comentado');
    ('    R - Resumo técnico');
    ('    N - Nova consulta');
    ('    F - Fim');
icDica
    ('Dica: pense no Diagnóstico como sendo um retrato da Situação Atual,');
    ('      nas Linhas Móveis como sendo Conselhos ou Comentários');
    ('      e no Prognóstico como sendo a Situação Futura ou Resposta');

icerrdos Erro no Sistema Operacional

iccara   Cara
iccoroa  Coroa
icpin    ...pin...
iclinha  Linha ...
icconti  Continua
icquebr  Quebrada

icdiag   Diagnóstico:
icmutac  Mutações:
icdiag   Prognóstico:
ichexag  Hexagrama:
ictodas  Todas as linhas, caso especial !
icnenhum Nenhuma

icjulg   Julgamento:
icimag   Imagem:
iclinmov Linhas móveis:

icerrdsk Erro de escrita no disco
icarqfal Arquivos de texto faltando, gravação cancelada.
icarqnao Arquivo de textos não encontrado.  Reinstale o programa !
icarqdan Arquivo de textos danificado.  Reinstale o programa !

icform   Formado pelos seguintes trigramas:

icquerex Deseja explicações (S/N) ?

ichex1  O CRIATIVO
ichex2  O RECEPTIVO
ichex3  DIFICULDADE INICIAL
ichex4  A INSENSATEZ JUVENIL
ichex5  A ESPERA (NUTRICAO)
ichex6  CONFLITO
ichex7  O EXÉRCITO
ichex8  MANTER-SE UNIDO (SOLIDARIEDADE)
ichex9  O PODER DE DOMAR DO PEQUENO
ichex10 A CONDUTA (TRILHAR)
ichex11 PAZ
ichex12 ESTAGNAÇÃO
ichex13 COMUNIDADE COM OS HOMENS
ichex14 GRANDES POSSES
ichex15 MODÉSTIA
ichex16 ENTUSIASMO
ichex17 SEGUIR
ichex18 TRABALHO SOBRE O QUE SE DETERIOROU
ichex19 APROXIMAÇÃO
ichex20 CONTEMPLAÇÃO (A VISTA)
ichex21 MORDER
ichex22 GRACIOSIDADE (BELEZA)
ichex23 DESINTEGRAÇÃO
ichex24 RETORNO (O PONTO DE TRANSIÇÃO)
ichex25 INOCÊNCIA (O INESPERADO)
ichex26 O PODER DE DOMAR DO GRANDE
ichex27 AS BORDAS DA BOCA (PROVER ALIMENTO)
ichex28 PREPONDERÂNCIA DO GRANDE
ichex29 O ABISMAL (AGUA)
ichex30 ADERIR (FOGO)
ichex31 A INFLUÊNCIA (CORTEJAR)
ichex32 DURAÇÃO
ichex33 A RETIRADA
ichex34 O PODER DO GRANDE
ichex35 PROGRESSO
ichex36 OBSCURECIMENTO DA LUZ
ichex37 A FAMÍLIA
ichex38 OPOSIÇÃO
ichex39 OBSTRUÇÃO
ichex40 LIBERAÇÃO
ichex41 DIMINUIÇÃO
ichex42 AUMENTO
ichex43 IRROMPER (A DETERMINAÇÃO)
ichex44 VIR AO ENCONTRO
ichex45 REUNIÃO
ichex46 ASCENSÃO
ichex47 OPRESSÃO (A EXAUSTÃO)
ichex48 O POCO
ichex49 REVOLUÇÃO
ichex50 O CALDEIRÃO
ichex51 O INCITAR (COMOÇÃO, TROVÃO)
ichex52 A QUIETUDE (MONTANHA)
ichex53 DESENVOLVIMENTO (PROGRESSO GRADUAL)
ichex54 A JOVEM QUE SE CASA
ichex55 ABUNDÂNCIA (PLENITUDE)
ichex56 O VIAJANTE
ichex57 A SUAVIDADE (O PENETRANTE, VENTO)
ichex58 ALEGRIA (LAGO)
ichex59 DISPERSÃO (DISSOLUÇÃO)
ichex60 LIMITAÇÃO
ichex61 VERDADE INTERIOR
ichex62 A PREPONDERÃNCIA DO PEQUENO
ichex63 APÓS A CONCLUSÃO
ichex64 ANTES DA CONCLUSÃO

icper0  O CRIATIVO,  A FIGURA DO CEU
icper1  O RECEPTIVO, A FIGURA DA TERRA
icper2  O INCITAR,   A FIGURA DO TROVAO
icper3  O ABISMAL,   A FIGURA DA AGUA
icper4  A QUIETUDE,  A FIGURA DA MONTANHA
icper5  A SUAVIDADE, A FIGURA DO VENTO ou MADEIRA
icper6  O ADERIR,    A FIGURA DO FOGO
icper7  A ALEGRIA,   A FIGURA DO LAGO
