CTSNHSM     Servidor SMTP opera com senha
CTNSNHSM    Servidor SMTP não precisa senha
MWINIC      Mini servidor WEB - versão
MWDIRNAO    Diretório para publicar não existe
MWPFCONF    Por favor, configure este servidor.
MWDESCNF    Deseja configurar o servidor ?
MWENTACE    Nas perguntas a seguir aperte ENTER se ok, ou responda novo valor.
MWCNFSER    Configurando
MWINFDIR    Informe o diretório para publicar, atualmente
MWDIRNAO    Diretório para publicar não existe
MWPRGCAN    Programa cancelado
MWINFNCN    Número máximo de clientes a servir, atualmente
MWINFPOR    Informe a porta do servidor, atualmente
MWINFCOR    Informe o servidor smtp usado na gerência, atualmente
MWINFCON    Informe a conta do gerenciador, atualmente
MWINFEMA    Informe sua conta de email, atualmente
MWINFNOM    Informe seu nome, atualmente
MWINFLOG    Informe o arquivo para registro dos pedidos, atualmente
CTFIMCNF    Fim da configuração
NWESPCON    Esperando conexão na porta...
MWERRLOG    Erro ao gerar arquivo de registro
MWFIMSRV    Fim do servidor Miniweb
MWF1        As opções do programa são
MWF4        F4 para configurar
MWF5        F5 para saber quantas conexões ativas
MWF6        F6 para saber endereço IP
MWESC       ESC para sair
MWPARALI    Servidor foi paralisado para reconfigurar
MWNCLI      Número de clientes ativos:
MWENDIP     Meu endereço IP é
MWCNFFIM    Confirma fim?
MWERRCOR    Não consegui enviar os proclamas pelo correio
MWPROCLA    Proclamas foram enviados pelo correio
