CHESCDSJ    Selecione com as setas o campo desajustado e aperte enter
CHSELDSL    Selecione agora o deslocamento a realizar
CHOK        OK.
CHESQ       Esquerda
CHDIR       Direita
CHCIMA      Cima
CHBAIXO     Baixo
CHNOME      Nome
CHIDENT     Identidade
CHEXPEDI    Expedidor
CHCPF       CPF
CHTELEFO    Telefone
CHENDERE    Endereço
CHBAIRRO    Bairro
CHCIDADE    Cidade
CHARQLAN    Nome do Arquivo Lançamento
CHANO4      Escreve ano com 4 digitos
CHIMPDEI    Imprime cheque deitado
CHRESTAU    Restaura posições originais
CHMILDIR    Milímetros para a direita
CHMILESQ    Milímetros para baixo
CHAJUAGO    Ajusta a impressão agora
CHDATA      Data
CHTIPDOC    Tipo do documento
CHVALDOC    Valor
CHDEBCRE    Débito ou crédito?
CHNUMSER    *Número de Série
CHNUMDOC    *Número do documento
CHFAVDOC    *Favorecido
CHFINDOC    *Finalidade
CHVALOR     Valor
CHFAVORE    Favorecido
CHCIDEMI    Cidade de emissão
CHDATEMI    Data da emissão
CHCHCRUZ    Cheque é cruzado
CHFINALI    *Finalidade
CHSERCHQ    *Série do cheque
CHNUMCHQ    *Número do cheque
CHVALOR     Valor
CHEXT1      Primeiro número extenso
CHEXT2      Segundo número extenso
CHFAVORE    Favorecido
CHCIDADE    Cidade
CHDIA       Dia
CHMES       Mês
CHANO       Ano
CHDESAJU    Selecione com as setas o campo desajustado e aperte enter
CHSELDSL    Escolha com as setas a direção a deslocar e aperte enter
CHINFMIL    Quantos milímetros desloco ?
