;Insira novos efeitos e modelos seguindo exatamente os exemplos abaixo
;Linhas iniciadas com ';' serão consideradas comentários
;Linhas iniciadas com '*' serão consideradas modelos
;Maiores informações, consulte o manual: c:\winvox\manual\metrovox.txt
;
[EFEITOS]
baqueta tradicional=baqueta
caixa com esteira frouxa=caixa1
caixa com esteira=caixa2
simbal preso=prato2
simbal solto=prato1
metrônomo original 1=metro1
metrônomo original 2=metro2
panderola=panderol
prato de condução=prato3
prato chaina=prato4
som de bip 1=bip1
som de bip 2=bip2
tom 12=tom12
tom 13=tom13
;
[MODELOS]
*01 metrônomo original 1 e som de bip 2=metro1/bip2
*02 panderola e baqueta tradicional=panderol/baqueta
*03 tom 12 e baqueta tradicional=tom12/baqueta
*04 tom 13 e padrão 2=tom13/padrao2
*05 caixa com esteira frouxa e simbal preso=caixa1/prato2
*06 prato de condução e baqueta tradicional=prato3/baqueta
*07 caixa com esteira e metrônomo original 2=caixa2/metro2
