;-----------------------------------------------
;      modelo para configuração do cartavox
;-----------------------------------------------

[modelo]
SERVIDORSMTP=smtp.servidor.com.br
SMTPCOMSENHA=NAO
SMTPCOMSSL=NAO
SMTPCOMTLS=NAO
PORTASMTP=25
SERVIDORPOP3=pop.servidor.com.br
USASSL=NAO
PORTAPOP3=110
SERVIDORIMAP=imap.servidor.com.br
IMAPUSASSL=NAO
PORTAIMAP=143
ENDERRESPOSTA=
ENDERUSUARIO=fulano@servidor.com.br
CONTAUSUARIO=fulano
NOMEUSUARIO=Fulano de Tal
DIRRECEBE=@@\e-mail
DIRENVIA=@@\e-mail
DIRANEXO=
LIMITEAUTOREC=10000000
ASSINATURA=
APELIDOS=@@\apelidos.ini
COPIAENVIADAS=SIM
ARMAZENASENHA=NAO
SCCV=
APLICARREGRAS=NAO
INSERIRASSINATURA=NAO
INSERIRCONFIRMACAOLEITURA=NAO
ARQRESPAUT=
ASSRESPAUT=
SIGRESPAUT=NAO
GRUPODECONTAS=NAO
TEMPOREMONITORAR=60
AVISANOVASNOMONITORAR=NAO
RECEBERAUTONOMONITORAR=NAO
CONFIGURACAO=

[intervox]
SERVIDORIMAP=intervox.nce.ufrj.br
IMAPUSASSL=NAO
PORTAIMAP=143
SERVIDORSMTP=caec.nce.ufrj.br
PORTASMTP=25
SMTPCOMSSL=NAO
SMTPCOMTLS=NAO
SMTPCOMSENHA=NAO
SERVIDORPOP3=intervox.nce.ufrj.br
USASSL=NAO
PORTAPOP3=110
ENDERUSUARIO=<conta>@intervox.nce.ufrj.br
CONTAUSUARIO=<conta>
NOMEUSUARIO=<nome>

[gmail]
SERVIDORIMAP=imap.gmail.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.gmail.com
PORTASMTP=587
SMTPCOMSSL=NAO
SMTPCOMTLS=SIM
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.gmail.com
PORTAPOP3=995
USASSL=SIM
ENDERUSUARIO=<conta>@gmail.com
CONTAUSUARIO=<conta>@gmail.com
NOMEUSUARIO=<nome>

[hotmail]
SERVIDORIMAP=imap-mail.outlook.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.office365.com
PORTASMTP=587
SMTPCOMSSL=NAO
SMTPCOMTLS=SIM
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop3.live.com
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@hotmail.com
CONTAUSUARIO=<conta>@hotmail.com
NOMEUSUARIO=<nome>

[live]
SERVIDORIMAP=imap.live.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.live.com
PORTASMTP=587
SMTPCOMSSL=NAO
SMTPCOMTLS=SIM
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop3.live.com
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@live.com
CONTAUSUARIO=<conta>@live.com
NOMEUSUARIO=<nome>

[outlook.com]
SERVIDORIMAP=outlook.office365.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.office365.com
PORTASMTP=587
SMTPCOMSSL=NAO
SMTPCOMTLS=SIM
SMTPCOMSENHA=SIM
SERVIDORPOP3=outlook.office365.com
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@outlook.com
CONTAUSUARIO=<conta>@outlook.com
NOMEUSUARIO=<nome>

[click21]
SERVIDORIMAP=imap.click21.com.br
IMAPUSASSL=NAO
PORTAIMAP=143
SERVIDORSMTP=smtp.click21.com.br
PORTASMTP=25
SMTPCOMSSL=NAO
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.click21.com.br
USASSL=NAO
PORTAPOP3=110
ENDERUSUARIO=<conta>@click21.com.br
CONTAUSUARIO=<conta>@click21.com.br
NOMEUSUARIO=<nome>

[yahoo.com.br]
SERVIDORIMAP=imap.mail.yahoo.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.mail.yahoo.com.br
PORTASMTP=465
SMTPCOMSSL=SIM
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.mail.yahoo.com.br
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@yahoo.com.br
CONTAUSUARIO=<conta>
NOMEUSUARIO=<nome>

[yahoo.com]
SERVIDORIMAP=imap.mail.yahoo.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.mail.yahoo.com
PORTASMTP=465
SMTPCOMSSL=SIM
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.mail.yahoo.com
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@yahoo.com
CONTAUSUARIO=<conta>
NOMEUSUARIO=<nome>

[globo.com]
SERVIDORIMAP=imap.globo.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.globo.com
PORTASMTP=465
SMTPCOMSSL=SIM
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.globo.com
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@globo.com
CONTAUSUARIO=<conta>@globo.com
NOMEUSUARIO=<nome>

[globomail.com]
SERVIDORIMAP=imap.globo.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.globo.com
PORTASMTP=465
SMTPCOMSSL=SIM
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.globo.com
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@globomail.com
CONTAUSUARIO=<conta>@globomail.com
NOMEUSUARIO=<nome>

[saci]
SERVIDORIMAP=imap.saci.org.br
IMAPUSASSL=NAO
PORTAIMAP=143
SERVIDORSMTP=saci.org.br
PORTASMTP=25
SMTPCOMSSL=NAO
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=saci.org.br
USASSL=NAO
PORTAPOP3=110
ENDERUSUARIO=<conta>@saci.org.br
CONTAUSUARIO=<conta>
NOMEUSUARIO=<nome>

[terra com segurança]
SERVIDORIMAP=imap.terra.com.br
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.terra.com.br
PORTASMTP=465
SMTPCOMSSL=SIM
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.terra.com.br
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@terra.com.br
CONTAUSUARIO=<conta>@terra.com.br
NOMEUSUARIO=<nome>

[terra sem segurança]
SERVIDORIMAP=imap.terra.com.br
IMAPUSASSL=NAO
PORTAIMAP=143
SERVIDORSMTP=smtp.terra.com.br
PORTASMTP=465
SMTPCOMSSL=SIM
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.terra.com.br
USASSL=NAO
PORTAPOP3=110
ENDERUSUARIO=<conta>@terra.com.br
CONTAUSUARIO=<conta>@terra.com.br
NOMEUSUARIO=<nome>

[uol]
SERVIDORIMAP=imap.uol.com.br
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtps.uol.com.br
PORTASMTP=587
SMTPCOMSSL=NAO
SMTPCOMTLS=SIM
;PORTASMTP=465
;SMTPCOMSSL=SIM
;SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop3.uol.com.br
USASSL=SIM
PORTAPOP3=995
;USASSL=NAO
;PORTAPOP3=110
ENDERUSUARIO=<conta>@uol.com.br
CONTAUSUARIO=<conta>
NOMEUSUARIO=<nome>

[bol]
SERVIDORIMAP=imap.bol.com.br
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtps.bol.com.br
PORTASMTP=587
SMTPCOMSSL=NAO
SMTPCOMTLS=SIM
;PORTASMTP=465
;SMTPCOMSSL=SIM
;SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.bol.com.br
PORTAPOP3=995
USASSL=SIM
;PORTAPOP3=110
;USASSL=NAO
ENDERUSUARIO=<conta>@bol.com.br
CONTAUSUARIO=<conta>
NOMEUSUARIO=<nome>

[ig]
SERVIDORIMAP=imap.ig.com.br
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.ig.com.br
PORTASMTP=465
SMTPCOMSSL=SIM
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop3.ig.com.br
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@ig.com.br
CONTAUSUARIO=<conta>@ig.com.br
NOMEUSUARIO=<nome>

[itelefonica]
SERVIDORIMAP=imap.itelefonica.com
IMAPUSASSL=NAO
PORTAIMAP=143
SERVIDORSMTP=smtp.itelefonica.com.br
PORTASMTP=25
SMTPCOMSSL=NAO
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.itelefonica.com.br
USASSL=NAO
PORTAPOP3=110
ENDERUSUARIO=<conta>@itelefonica.com.br
CONTAUSUARIO=<conta>
NOMEUSUARIO=<nome>

[oi]
SERVIDORIMAP=imap.oi.com.br
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.oi.com.br
PORTASMTP=587
SMTPCOMSSL=NAO
SMTPCOMTLS=SIM
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.oi.com.br
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@oi.com.br
CONTAUSUARIO=<conta>@oi.com.br
NOMEUSUARIO=<nome>

[mundocegal]
SERVIDORIMAP=imap.mundocegal.com.br
IMAPUSASSL=NAO
PORTAIMAP=143
SERVIDORSMTP=mail.mundocegal.com.br
PORTASMTP=25
SMTPCOMSSL=NAO
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=mail.mundocegal.com.br
USASSL=NAO
PORTAPOP3=110
ENDERUSUARIO=<conta>@mundocegal.com.br
CONTAUSUARIO=<conta>@mundocegal.com.br
NOMEUSUARIO=<nome>

[pop]
SERVIDORIMAP=imap.pop.com.br
IMAPUSASSL=NAO
PORTAIMAP=143
SERVIDORSMTP=smtp.pop.com.br
PORTASMTP=25
SMTPCOMSSL=NAO
SMTPCOMTLS=NAO
SMTPCOMSENHA=NAO
SERVIDORPOP3=pop.pop.com.br
USASSL=NAO
PORTAPOP3=110
ENDERUSUARIO=<conta>@pop.com.br
CONTAUSUARIO=<conta>@pop.com.br
NOMEUSUARIO=<nome>

[ymail]
SERVIDORIMAP=imap.mail.yahoo.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.mail.yahoo.com.br
PORTASMTP=465
SMTPCOMSSL=SIM
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.mail.yahoo.com.br
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@ymail.com
CONTAUSUARIO=<conta>@ymail.com
NOMEUSUARIO=<nome>

[predialNet]
SERVIDORIMAP=imap.mail.predialnet.com.br
IMAPUSASSL=NAO
PORTAIMAP=143
SERVIDORSMTP=mail.predialnet.com.br
PORTASMTP=25
SMTPCOMSSL=NAO
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=mail.predialnet.com.br
USASSL=NAO
PORTAPOP3=110
ENDERUSUARIO=<conta>@servidor.com.br
CONTAUSUARIO=<conta>@servidor.com.br
NOMEUSUARIO=<nome>

[r7]
SERVIDORIMAP=imap.r7.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.r7.com
PORTASMTP=465
SMTPCOMSSL=SIM
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.r7.com
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@r7.com
CONTAUSUARIO=<conta>@r7.com
NOMEUSUARIO=<nome>

[sapo]
SERVIDORIMAP=imap.sapo.pt
IMAPUSASSL=NAO
SERVIDORSMTP=smtp.sapo.pt
PORTASMTP=587
SMTPCOMSSL=NAO
SMTPCOMTLS=NAO
SMTPCOMSENHA=NAO
SERVIDORPOP3=pop.sapo.pt
USASSL=NAO
PORTAPOP3=995
ENDERUSUARIO=<conta>@sapo.pt
CONTAUSUARIO=<conta>@sapo.pt
NOMEUSUARIO=<nome>

[acessibilidadeEmFoco]
SERVIDORIMAP=imap.hostinger.com
IMAPUSASSL=SIM
PORTAIMAP=993
SERVIDORSMTP=smtp.hostinger.com
PORTASMTP=587
SMTPCOMSSL=NAO
SMTPCOMTLS=SIM
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop.hostinger.com
USASSL=SIM
PORTAPOP3=995
ENDERUSUARIO=<conta>@acessibilidadeemfoco.com
CONTAUSUARIO=<conta>@acessibilidadeemfoco.com
NOMEUSUARIO=<nome>

[servidor genérico]
SERVIDORIMAP=imap.servidor.com.br
IMAPUSASSL=NAO
PORTAIMAP=143
SERVIDORSMTP=smtp.servidor.com.br
PORTASMTP=25
SMTPCOMSSL=NAO
SMTPCOMTLS=NAO
SMTPCOMSENHA=SIM
SERVIDORPOP3=pop3.servidor.com.br
USASSL=NAO
PORTAPOP3=110
ENDERUSUARIO=<conta>@servidor.com.br
CONTAUSUARIO=<conta>
NOMEUSUARIO=<nome>
