; Nomes dos arquivos de som para o webvox

HEAD=
/HEAD=
TITLE=detalhe\title
/TITLE=detalhe\$title
BODY=
/BODY=
CENTER=detalhe\center
/CENTER=detalhe\$center
BR=
P=detalhe\p
B=detalhe\b
/B=detalhe\$b
I=detalhe\i
/I=detalhe\$i
MARQUEE=detalhe\marquee
/MARQUEE=detalhe\$marquee
HR=detalhe\hr
PRE=
/PRE=
TABLE=
/TABLE=
CAPTION=
/CAPTION=
TH=
/TH=
TD=
/TD=
TR=
SCRIPT=
/SCRIPT=
IMG=detalhe\img
UL=
/UL=
OL=
/OL=
LI=
DL=
/DL=
MAP=
AREA=
AREA HREF=
A NAME=
A HREF=detalhe\href
/A=
FRAMESET=
FRAME=
NOFRAMES=
FORM=detalhe\form
/FORM=detalhe\$form
INPUT=
TEXTAREA=
/TEXTAREA=
SELECT=
/SELECT=
OPTION=
H1=
/H1=
H2=
/H2=
H3=
/H3=
H4=
/H4=
H5=
/H5=
H6=
/H6=
FONT=
/FONT=
