Os comandos do formatador são os seguintes:

a) comandos de margem e espacejamento

<MS=valor>     margem superior
<MI=valor>     margem inferior
<ME=valor>     margem esquerda
<MD=valor>     margem direita
<EL=valor>     espacejamento entre linhas

b) titulo e paginacao

<Ttexto>       Título
<NT>           Não titula a partir deste local
<P>            Forca salto de pagina

c) alinhamento e separacao de silabas

<AL>           Faz alinhamento `a direita das linhas
<NAL>          Nao faz alinhamento `a direita das linhas
<SS>           Separa silabas
<NSS>          Nao separa silabas

d) Tipo de letra

<IN>           Inicio de texto negritado
<FN>           Fim de texto negritado
<IS>           Inicio de texto sublinhado
<FS>           Fim de texto sublinhado
<II>           Inicio de texto em italico
<FI>           Fim de texto em italico
<ISO>          Inicio de texto sobreescrito
<FSO>          Fim de texto sobrescrito
<ISU>          Inicio de texto subescrito
<FSU>          Fim de texto subescrito

e) forçar quebra de paragrafo

<NL>           Passa imediatamente para a proxima linha

f) rodapé

<IROD>         Início de rodapé
<FROD>         Fim de Rodapé